name: ai_object_remover
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  nb_utils: ^7.0.6
  flutter_svg: ^2.0.7
  get: ^4.6.6
  url_launcher: ^6.1.12
  font_awesome_flutter: ^10.5.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  intl:
  



dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

 #body fonts
  fonts: 
    - family: Poppins
      fonts: 
        - asset: fonts/PoppinsRegular.ttf
        
    # #handing fonts
    # - family: futurbci
    #   fonts: 
    #     - asset: fonts/futurbci.ttf
    
